name: Publish site
on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build and publish site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          python -m pip install -r requirements.txt
          python opportunities.py
          rm public/.gitignore
        env:
          HAVELOC_API_KEY: ${{ secrets.HAVELOC_API_KEY }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
