name: Publish site
on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build and publish site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate site
        run: |
          python -m pip install -r requirements.txt
          python opportunities.py
          rm public/.gitignore
        env:
          HAVELOC_API_KEY: ${{ secrets.HAVELOC_API_KEY }}

      - name: Push generated site to `gh-pages` branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          force_orphan: true
